# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GsipLod
                                 A QGIS plugin
 GSIP linked open data browser
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-11
        copyright            : (C) 2019 by Geological Survey of Canada - Laboratoire de cartographie numérique et de photogrammétrie
        email                : eric.boisvert2@canada.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GsipLod class from file GsipLod.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gsip_load import GsipLod
    return GsipLod(iface)
